#!/bin/bash

if [ -f "Backup/tmp/Google_Earth.kml" ]; then
	rm Backup/tmp/Google_Earth.kml
fi

echo "Criando o arquivo de GPS no estilo Google Earth" 

awk 'BEGIN {print "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<kml xmlns=\"http://www.opengis.net/kml/2.2\"> \
\n<Document>\n<Style id=\"marker\">\n<IconStyle> \
\n<Icon><href>http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png</href></Icon> \
\n</IconStyle>\n</Style>"} \
{print "<Placemark><styleUrl>#marker</styleUrl><description><![CDATA[<h2>"$1"</h2><img src="$1" style=\"width:150px;height:200;\">]]></description><Point><coordinates>"$3","$2",0</coordinates></Point></Placemark>"} \
END {print "</Document>\n</kml>"}' Backup/tmp/GPS_FILE > Backup/tmp/Google_Earth.kml
echo "Pronto"

# ==========================================================

echo "Criando o arquivo de GPS no estilo Viking"

if [ -f "Backup/tmp/Viking.vik" ]; then
	rm Backup/tmp/Viking.vik
fi

echo "#VIKING GPS Data file http://viking.sf.net/
FILE_VERSION=1

xmpp=16.000000
ympp=16.000000
lat=33.455972
lon=-111.964722
mode=mercator
color=#cccccc
highlightcolor=#eea500
drawscale=t
drawcentermark=t
drawhighlight=t

~Layer Map
name=Map
mode=13
directory=
cache_type=1
mapfile=
alpha=255
autodownload=t
adlonlymissing=f
mapzoom=0
~EndLayer


~Layer TrackWaypoint
name=Viking.vik
tracks_visible=t
waypoints_visible=t
routes_visible=t
trackdrawlabels=t
trackfontsize=3
drawmode=0
trackcolor=#000000
drawlines=t
line_thickness=1
drawdirections=f
trkdirectionsize=5
drawpoints=t
trkpointsize=2
drawelevation=f
elevation_factor=30
drawstops=f
stop_length=60
bg_line_thickness=0
trackbgcolor=#ffffff
speed_factor=30.000000
tracksortorder=0
drawlabels=t
wpfontsize=3
wpcolor=#000000
wptextcolor=#ffffff
wpbgcolor=#8383c4
wpbgand=f
wpsymbol=0
wpsize=4
wpsyms=t
wpsortorder=0
drawimages=t
image_size=64
image_alpha=255
image_cache_size=300
metadatadesc=
metadataauthor=
metadatatime=2019-08-02T23:41:36.714357Z
metadatakeywords=
external_layer=0
external_file=

~LayerData
type="waypointlist"
" >> Backup/tmp/Viking.vik

while read p; do
name=`echo $p | awk '{print $1}'`
lat=`echo $p | awk '{print $2}'`
long=`echo $p | awk '{print $3}'`

echo "type=\"waypoint\" latitude=\"$lat\" longitude=\"$long\" name=\"$name\" unixtime=\"0\" comment=\"$name\" description=\"$name\" image=\"`pwd`/Backup/Camera/$name\""

done < Backup/tmp/GPS_FILE >> Backup/tmp/Viking.vik

echo "type="waypointlistend"
~EndLayerData
~EndLayer
" >> Backup/tmp/Viking.vik

echo "Pronto!"
